---
title: "Comparison of Sentiment Tools across Domains"
output: html_notebook
---

Hint:
Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Cmd+Shift+Enter*. 

```{r}
# load required libraries

# to use harry potter dataset
# devtools::install_github("bradleyboehmke/harrypotter")
# devtools::install_github("quanteda/quanteda.sentiment")
# devtools::install_github("quanteda/quanteda.corpora")



library(quanteda)
library(readtext)
library(corpus)
library(tidyverse)
library(stringr)
library(tidytext)
library(harrypotter)
library(janeaustenr)
library(dplyr)
library(quanteda.sentiment)
library(vader)

```

```{r}
# load afinn lexicon

# manually -> convert to binary lexicon
afinn_dict <- read.csv("lexika/AFINN-111.txt", header = F, sep = "\t", stringsAsFactors = F)
afinn_binary <- dictionary(list(positive = afinn_dict$V1[afinn_dict$V2>0], negative = afinn_dict$V1[afinn_dict$V2<0]))

# provided via tidytext?
afinn <- get_sentiments("afinn")

```

```{r}
dfm.sentiment <- dfm(korpus, dictionary = afinn_binary)

dfm.sentiment
```
# Harry Potter - Dataset
```{r}
# load harry potter dataset 
titles <- c("Philosopher's Stone", "Chamber of Secrets", "Prisoner of Azkaban",
            "Goblet of Fire", "Order of the Phoenix", "Half-Blood Prince",
            "Deathly Hallows")

books <- list(philosophers_stone, chamber_of_secrets, prisoner_of_azkaban,
           goblet_of_fire, order_of_the_phoenix, half_blood_prince,
           deathly_hallows)
  
series <- tibble()

for(i in seq_along(titles)) {
        
        clean <- tibble(chapter = seq_along(books[[i]]),
                        text = books[[i]]) %>%
             unnest_tokens(word, text) %>%
             mutate(book = titles[i]) %>%
             select(book, everything())

        series <- rbind(series, clean)
}

series$book <- factor(series$book, levels = rev(titles))

series
```
```{r}
hp_corpus <- corpus(books)

```

### Harry Potter - AFINN Lexicon
```{r}
afinn_hp1 <- series %>%
        group_by(book) %>% 
        mutate(word_count = 1:n(),
               index = word_count %/% 500 + 1) %>% 
        inner_join(get_sentiments("afinn")) %>%
        group_by(book, index, chapter) %>%
        summarise(sentiment = sum(value)) %>%
        mutate(method = "AFINN")

afinn_hp1
```

```{r}
afinn_hp2 <- series %>%
        group_by(book, chapter) %>% # add word for single word scores 
        inner_join(get_sentiments("afinn")) %>%
        group_by(book, chapter) %>% # add word for single word scores
        #summarise(sentiment = sum(value)) %>%
        summarise(sentiment = mean(value, na.rm = TRUE)) %>%
        mutate(method = "AFINN")  %>%
        ggplot(aes(chapter, sentiment, fill = book)) +
          geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE) +
          facet_wrap(~ book, ncol = 2, scales = "free_x")

afinn_hp2

#ggsave(plot = afinn, width = 15, height = 15, dpi = 300, filename = "afinn_hp_mean.png")
```

# Jane Austen - Dataset
```{r}
tidy_books <- austen_books() %>%
  group_by(book) %>%
  mutate(
    linenumber = row_number(),
    chapter = cumsum(str_detect(text, 
                                regex("^chapter [\\divxlc]", 
                                      ignore_case = TRUE)))) %>%
  ungroup() %>%
  unnest_tokens(word, text)
```
```{r}
pride_prejudice <- tidy_books %>% 
  filter(book == "Pride & Prejudice")
```

### Jane Austen - AFINN Lexicon
```{r}
afinn_austen <- pride_prejudice %>% 
  inner_join(get_sentiments("afinn")) %>% 
  group_by(index = linenumber %/% 80) %>% 
  summarise(sentiment = sum(value)) %>% 
  mutate(method = "AFINN")
```

### NOT WORKING:
```{r}
afinn2 <- data_dictionary_AFINN

afinn2


data_dictionary_LSD2015_pos_neg <- data_dictionary_LSD2015[1:2]
data_dictionary_LSD2015
```
```{r}
library("quanteda", warn.conflicts = FALSE, quietly = TRUE)
print(data_dictionary_AFINN, max_nval = 8)
```

# Lexicoder Sentiment Dictionary
```{r}
require(quanteda)
require(quanteda.corpora)
require(quanteda.sentiment)
```

```{r}
# tokenize corpus
hp1_tokenized <- tokens(philosophers_stone, remove_punct = TRUE)
```

```{r}
# select only the "negative" and "positive" categories
#data_dictionary_LSD2015_pos_neg <- data_dictionary_LSD2015[1:2]

#hp1_lsd <- tokens_lookup(hp1_tokenized, dictionary = data_dictionary_LSD2015_pos_neg)

polarity(data_dictionary_LSD2015) <- 
  list(pos = c("positive", "neg_negative"), neg = c("negative", "neg_positive"))

hp1_lsd <- textstat_polarity(hp1_tokenized, data_dictionary_LSD2015)

hp1_lsd_tokens <- tokens_lookup(hp1_tokenized, data_dictionary_LSD2015, nested_scope = "dictionary", exclusive = FALSE)
```

```{r}
# hp1_lsd_tokens
hp1_lsd.df <- as.data.frame.matrix(hp1_lsd)

hp1_lsd.df$chapter <- 1:nrow(hp1_lsd.df)

plot <- ggplot(hp1_lsd, aes(x =hp1_lsd.df$chapter, y=sentiment)) +
          geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE)
plot + ylim(-1.0, 1.0) + labs(y="sentiment", x = "chapter") + ggtitle("HP1 - Lexicoder")

#hp1_lsd.df

```

```{r}
hp1_afinn2 <- textstat_valence(hp1_tokenized, afinn2)

hp1_afinn2.df <- as.data.frame.matrix(hp1_afinn2)

hp1_afinn2.df$chapter <- 1:nrow(hp1_afinn2.df)

plot <- ggplot(hp1_afinn2.df, aes(x =hp1_afinn2.df$chapter, y=sentiment)) +
          geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE)
plot + ylim(-1.0, 1.0) + labs(y="sentiment", x = "chapter") + ggtitle("HP1 - AFINN")
```
```{r}
afinn_hp_all <- series %>%
        group_by(book, chapter) %>% # add word for single word scores 
        tokens() %>%
        as.data.frame.matrix() %>%
        #inner_join(get_sentiments("afinn")) %>%
        textstat_valence(series, afinn2) %>%
        group_by(book, chapter) %>% # add word for single word scores
        #summarise(sentiment = sum(value)) %>%
        #summarise(sentiment = mean(value, na.rm = TRUE)) %>%
        mutate(method = "AFINN")  %>%
        ggplot(aes(chapter, sentiment, fill = book)) +
          geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE) +
          facet_wrap(~ book, ncol = 2, scales = "free_x")

afinn_hp_all

series
```


# VADER

```{r}
get_vader(philosophers_stone[1])

hp1_vader <- vader_df(philosophers_stone)
```
```{r}
hp1_vader


hp1_vader$chapter <- 1:nrow(hp1_vader)

plot <- ggplot(hp1_vader, aes(x =chapter, y=compound)) +
          geom_bar(alpha = 0.8, stat = "identity", show.legend = FALSE)
plot + ylim(-5.0, 5.0) + labs(y="sentiment", x = "chapter") + ggtitle("HP1 - VADER")
```
```{r}

```

```{r}
library("quanteda", warn.conflicts = FALSE, verbose = FALSE)
library("quanteda.sentiment", warn.conflicts = FALSE, verbose = FALSE)

print(data_dictionary_LSD2015, max_nval = 5)
lengths(data_dictionary_LSD2015)
```

```{r}
#Idee: für alle Harry Potter Teile durchlaufen lassen und plotten -> in Funktion so wie ganz oben für AFINN machen und abändern. 


```

